services:
  mysql:
    container_name: dam2_mysql
    image: mysql:latest
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: dam2_mysql
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: mysql
    networks:
      - prestashop_network
networks:
  prestashop_network: